name: master

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,23 * * *"
  push:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t .
          sudo sh install_dependencies.sh
      - name: Run master
        run: |
          python epicgames_claimer.py -u ${{ secrets.EPIC_EMAIL }} -p ${{ secrets.EPIC_PASSWORD }} -pda ${{ secrets.PUSH_DINGTALK_ACCESS_TOKEN }} -pds ${{ secrets.PUSH_DINGTALK_SECRET }} --once
